apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-reg-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
      - name: student-container
        image: your-docker-id/student-app:latest # Replace with your ID
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: student-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    app: student-app
